### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by kik-tibia** [tibiamaps/tibia-kill-stats#7]
Hi, there is no commit or data for `2023-05-21`.

What happened? Is it too late to get this data and commit it somehow? Might it happen again?

Thanks

**Comment by mathiasbynens** [comment]
Ugh, looks like something was wrong with tibia.com at the time, causing the API to return unexpected results: https://github.com/tibiamaps/tibia-kill-stats/actions/runs/5035448704/jobs/9030978119#step:5:21

I'm afraid it's too late to retroactively add data for that day :(

**Comment by mathiasbynens** [comment]
Addressed in 50b1f976d55c7b5303f9fa779c2eb82226f09ef8 and 3f07be76115e5c4de66cc8829d3b6eba9c4c556a. With these changes, we’ll try to get the data 3× instead of just once. It’s still possible that all 3 attempts fail but it should be more rare than just a singular failure.
